---

name: Adjust Card Case

on: 
  push: 
    branches: 
      - master
    paths:
      - 'Images-HT/starwars/**'
      - 'Images-HT/legacy/**'


jobs:
  deploy-holotable: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Create local changes
        run: |
          python3 case_fixer.py

      - name: Commit files
        run: |
          git config --local user.email "devon+github-actions[bot]@hubner.org"
          git config --local user.name "github-actions[bot]"
          git commit -m "Making MISSING gifs from hires pngs" -a ; true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

