---

name: Deploy Holotable

on: 
  push: 
    branches: 
      - master
    paths:
      - 'Images-HT/starwars/**'


jobs:
  deploy-holotable: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main

      - name: sync to s3
        run: aws s3 sync ./Images-HT/starwars/ s3://res.starwarsccg.org/cards/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude package-lock.json --exclude package.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}




