---

name: Update listmd5 and create release zip

on:
  push:
    branches:
      - master
    paths:
      - 'Images-HT/starwars/**'
      - 'Images-HT/*.gif'
      - 'darkside.cdf'
      - 'lightside.cdf'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        bash make_listmd5.sh
        python3 fix_bullets.py
        python3 make_version_dat.py
        bash make_release_zip.sh
    - name: Commit files
      run: |
        git config --local user.email "devon+github-actions[bot]@hubner.org"
        git config --local user.name "github-actions[bot]"
        git commit -m "updated listmd5 and release zip" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}



